-- ============================================================
-- 校园二手交易平台（第二手 SecondHand AI） 数据库建表脚本（PostgreSQL）
-- 设计人：田博（后端）  适用：PostgreSQL 15/16
-- 约定：主键 BIGINT IDENTITY；逻辑删除 deleted SMALLINT(0/1)；金额 DECIMAL(10,2)
-- 说明：updated_at 自动更新由统一触发器维护；中文检索使用 pg_trgm + ILIKE（业务层兜底）
-- ============================================================

CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ============================================================
-- 统一 updated_at 自动更新触发器
-- ============================================================
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================================
-- 清理旧对象（按依赖逆序）
-- ============================================================
DROP TABLE IF EXISTS ai_publish_draft;
DROP TABLE IF EXISTS ai_estimate_log;
DROP TABLE IF EXISTS carbon_credit;
DROP TABLE IF EXISTS carbon_record;
DROP TABLE IF EXISTS message;
DROP TABLE IF EXISTS review;
DROP TABLE IF EXISTS trade_order;
DROP TABLE IF EXISTS browse_history;
DROP TABLE IF EXISTS favorite;
DROP TABLE IF EXISTS product_image;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS user_credit;
DROP TABLE IF EXISTS "user";

-- ------------------------------------------------------------
-- 1. 用户表（基础字段；登录/权限由登录模块扩展）
-- ------------------------------------------------------------
CREATE TABLE "user" (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_no    VARCHAR(20)  NOT NULL,
    username      VARCHAR(50)  NOT NULL,
    name          VARCHAR(50)  NOT NULL DEFAULT '',
    nickname      VARCHAR(50),
    avatar        VARCHAR(255),
    phone         VARCHAR(20),
    email         VARCHAR(100),
    credit_score  INTEGER      NOT NULL DEFAULT 100,
    real_name_verified SMALLINT NOT NULL DEFAULT 0,
    is_student    SMALLINT     NOT NULL DEFAULT 1,
    status        SMALLINT     NOT NULL DEFAULT 1,
    deleted       SMALLINT     NOT NULL DEFAULT 0,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_student_no UNIQUE (student_no),
    CONSTRAINT uk_user_username UNIQUE (username)
);
CREATE INDEX idx_user_status ON "user" (status);

COMMENT ON TABLE  "user"            IS '用户表';
COMMENT ON COLUMN "user".id          IS '用户ID';
COMMENT ON COLUMN "user".student_no  IS '学号（实名认证）';
COMMENT ON COLUMN "user".username    IS '登录名';
COMMENT ON COLUMN "user".name        IS '真实姓名（注册/实名认证字段，规范5.1）';
COMMENT ON COLUMN "user".nickname    IS '昵称';
COMMENT ON COLUMN "user".avatar      IS '头像URL';
COMMENT ON COLUMN "user".credit_score IS '信用分（100起，冗余汇总）';
COMMENT ON COLUMN "user".real_name_verified IS '学号实名认证 0未认证 1已认证';
COMMENT ON COLUMN "user".is_student  IS '是否在校学生 0否 1是';
COMMENT ON COLUMN "user".status      IS '状态 0禁用 1正常';
COMMENT ON COLUMN "user".deleted     IS '逻辑删除 0否 1是';

-- ------------------------------------------------------------
-- 2. 信用分记录表（互评/交易行为增减，T1 重点表）
-- ------------------------------------------------------------
CREATE TABLE user_credit (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT      NOT NULL,
    change_amount     INTEGER     NOT NULL,
    reason_type       SMALLINT    NOT NULL,
    reason            VARCHAR(200),
    balance_after     INTEGER     NOT NULL,
    related_order_id  BIGINT,
    created_at        TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_credit_user ON user_credit (user_id, created_at);
CREATE INDEX idx_credit_order ON user_credit (related_order_id);

COMMENT ON TABLE  user_credit            IS '信用分变动记录表';
COMMENT ON COLUMN user_credit.change_amount IS '变动分值（正加负减）';
COMMENT ON COLUMN user_credit.reason_type   IS '类型 1交易成功 2互评好评 3互评差评 4违规 5举报成立 6申诉恢复 7签到';
COMMENT ON COLUMN user_credit.balance_after IS '变动后余额';

-- ------------------------------------------------------------
-- 3. 商品分类表（含 AI 估价规则参数）
-- ------------------------------------------------------------
CREATE TABLE category (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id         BIGINT      NOT NULL DEFAULT 0,
    name              VARCHAR(50) NOT NULL,
    icon              VARCHAR(255),
    base_price        DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    depreciation_rate DECIMAL(5,4)  NOT NULL DEFAULT 0.1500,
    heat_weight       DECIMAL(4,3)  NOT NULL DEFAULT 1.000,
    sort_order        INTEGER     NOT NULL DEFAULT 0,
    status            SMALLINT    NOT NULL DEFAULT 1,
    deleted           SMALLINT    NOT NULL DEFAULT 0,
    created_at        TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_category_parent ON category (parent_id);
CREATE INDEX idx_category_status_sort ON category (status, sort_order);

COMMENT ON TABLE  category IS '商品分类表（含AI估价参数）';
COMMENT ON COLUMN category.base_price IS 'AI估价基准价（该品类9成新基准）';
COMMENT ON COLUMN category.depreciation_rate IS '年折旧率（默认15%/年）';
COMMENT ON COLUMN category.heat_weight IS '市场热度系数（0.5~2.0）';

-- ------------------------------------------------------------
-- 4. 商品主表（核心业务表）
-- ------------------------------------------------------------
CREATE TABLE product (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id        BIGINT      NOT NULL,
    category_id      BIGINT      NOT NULL,
    title            VARCHAR(100) NOT NULL,
    description      TEXT,
    price            DECIMAL(10,2) NOT NULL,
    original_price   DECIMAL(10,2),
    estimated_price  DECIMAL(10,2),
    final_price      DECIMAL(10,2),
    condition_level  SMALLINT    NOT NULL DEFAULT 7,
    condition_desc   VARCHAR(200),
    tags             VARCHAR(255),
    location         VARCHAR(100),
    cover_image      VARCHAR(255),
    status           SMALLINT    NOT NULL DEFAULT 0,
    view_count       INTEGER     NOT NULL DEFAULT 0,
    favorite_count   INTEGER     NOT NULL DEFAULT 0,
    review_remark    VARCHAR(255),
    deleted          SMALLINT    NOT NULL DEFAULT 0,
    created_at       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_product_seller ON product (seller_id, status);
CREATE INDEX idx_product_category ON product (category_id, status);
CREATE INDEX idx_product_status_time ON product (status, created_at);
CREATE INDEX idx_product_price ON product (price);
-- 中文近似检索（pg_trgm；业务层 LIKE/ILIKE 兜底）
CREATE INDEX idx_product_title_trgm ON product USING gin (title gin_trgm_ops);
CREATE INDEX idx_product_desc_trgm ON product USING gin (description gin_trgm_ops);

COMMENT ON TABLE  product IS '商品主表';
COMMENT ON COLUMN product.price IS '期望售价';
COMMENT ON COLUMN product.original_price IS '原价/入手价（AI估价依据，规范7.1 originalPrice）';
COMMENT ON COLUMN product.estimated_price IS 'AI估价（可空）';
COMMENT ON COLUMN product.condition_level IS '成色等级 1~10（10=全新）';
COMMENT ON COLUMN product.status IS '状态 0草稿 1在售 2已下架 3已售出 4审核中 5审核驳回';
COMMENT ON COLUMN product.review_remark IS '审核驳回原因（管理员审核，规范6.5流程）';

-- ------------------------------------------------------------
-- 5. 商品图片表
-- ------------------------------------------------------------
CREATE TABLE product_image (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT      NOT NULL,
    url         VARCHAR(255) NOT NULL,
    sort_order  INTEGER     NOT NULL DEFAULT 0,
    created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_image_product ON product_image (product_id);
COMMENT ON TABLE product_image IS '商品图片表';

-- ------------------------------------------------------------
-- 6. 收藏表
-- ------------------------------------------------------------
CREATE TABLE favorite (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL,
    product_id  BIGINT      NOT NULL,
    created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_favorite_user_product UNIQUE (user_id, product_id)
);
CREATE INDEX idx_favorite_product ON favorite (product_id);
COMMENT ON TABLE favorite IS '收藏表';

-- ------------------------------------------------------------
-- 7. 浏览记录表
-- ------------------------------------------------------------
CREATE TABLE browse_history (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT      NOT NULL,
    product_id   BIGINT      NOT NULL,
    view_count   INTEGER     NOT NULL DEFAULT 1,
    last_view_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_history_user_product UNIQUE (user_id, product_id)
);
CREATE INDEX idx_history_user_time ON browse_history (user_id, last_view_at);
COMMENT ON TABLE browse_history IS '浏览记录表（同一商品合并计数）';

-- ------------------------------------------------------------
-- 8. 担保交易订单表（V1.0，T1 重点表，先建表）
-- ------------------------------------------------------------
CREATE TABLE trade_order (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no    VARCHAR(32)  NOT NULL,
    product_id  BIGINT      NOT NULL,
    buyer_id    BIGINT      NOT NULL,
    seller_id   BIGINT      NOT NULL,
    amount      DECIMAL(10,2) NOT NULL,
    status      SMALLINT    NOT NULL DEFAULT 0,
    pay_type    SMALLINT    NOT NULL DEFAULT 1,
    contact     VARCHAR(100),
    address     VARCHAR(255),
    remark      VARCHAR(255),
    paid_at     TIMESTAMP,
    finished_at TIMESTAMP,
    deleted     SMALLINT    NOT NULL DEFAULT 0,
    created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_order_no UNIQUE (order_no)
);
CREATE INDEX idx_order_buyer ON trade_order (buyer_id, status);
CREATE INDEX idx_order_seller ON trade_order (seller_id, status);
CREATE INDEX idx_order_product ON trade_order (product_id);

COMMENT ON TABLE  trade_order IS '担保交易订单表';
COMMENT ON COLUMN trade_order.status IS '状态 0待付款 1待发货 2待收货 3已完成 4已取消 5纠纷中';
COMMENT ON COLUMN trade_order.pay_type IS '支付方式 1线上担保';

-- ------------------------------------------------------------
-- 9. 买卖互评表（信用分依据，V1.0）
-- ------------------------------------------------------------
CREATE TABLE review (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT      NOT NULL,
    reviewer_id BIGINT      NOT NULL,
    reviewee_id BIGINT      NOT NULL,
    rating      SMALLINT    NOT NULL DEFAULT 5,
    content     VARCHAR(500),
    type        SMALLINT    NOT NULL DEFAULT 1,
    created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_review_order ON review (order_id);
CREATE INDEX idx_review_reviewee ON review (reviewee_id);

COMMENT ON TABLE  review IS '买卖互评表';
COMMENT ON COLUMN review.rating IS '评分 1~5';
COMMENT ON COLUMN review.type IS '类型 1买家评卖家 2卖家评买家';

-- ------------------------------------------------------------
-- 10. 站内私信表（林天楚模块，先建表统一字段）
-- ------------------------------------------------------------
CREATE TABLE message (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_user_id BIGINT       NOT NULL,
    to_user_id   BIGINT       NOT NULL,
    content      VARCHAR(1000) NOT NULL,
    type         SMALLINT     NOT NULL DEFAULT 1,
    is_read      SMALLINT     NOT NULL DEFAULT 0,
    deleted      SMALLINT     NOT NULL DEFAULT 0,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_message_to ON message (to_user_id, is_read, created_at);
CREATE INDEX idx_message_from ON message (from_user_id, created_at);

COMMENT ON TABLE  message IS '站内私信表';
COMMENT ON COLUMN message.type IS '类型 1私信 2系统通知';

-- ------------------------------------------------------------
-- 11. 减碳记录表（V1.0，T1 重点表）
-- ------------------------------------------------------------
CREATE TABLE carbon_record (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT       NOT NULL,
    record_type   SMALLINT     NOT NULL,
    product_id    BIGINT,
    carbon_amount DECIMAL(10,3) NOT NULL DEFAULT 0.000,
    description   VARCHAR(255),
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_carbon_user ON carbon_record (user_id, created_at);

COMMENT ON TABLE  carbon_record IS '减碳记录表';
COMMENT ON COLUMN carbon_record.record_type IS '类型 1卖出（避免新品生产） 2买入（代替新品）';
COMMENT ON COLUMN carbon_record.carbon_amount IS '减碳量（kg CO2e）';

-- ------------------------------------------------------------
-- 12. 环保积分账户表（V1.0）
-- ------------------------------------------------------------
CREATE TABLE carbon_credit (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT        NOT NULL,
    total_carbon DECIMAL(12,3) NOT NULL DEFAULT 0.000,
    total_points INTEGER       NOT NULL DEFAULT 0,
    updated_at   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_carbon_credit_user UNIQUE (user_id)
);
COMMENT ON TABLE  carbon_credit IS '环保积分账户表';
COMMENT ON COLUMN carbon_credit.total_carbon IS '累计减碳总量（kg CO2e）';
COMMENT ON COLUMN carbon_credit.total_points IS '环保积分（1kg=10积分示例）';

-- ------------------------------------------------------------
-- 13. AI 估价记录表（可追溯/可审计）
-- ------------------------------------------------------------
CREATE TABLE ai_estimate_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT,
    product_id      BIGINT,
    category_id     BIGINT,
    input_desc      VARCHAR(1000),
    base_price      DECIMAL(10,2),
    condition_score DECIMAL(4,2),
    age_months      INTEGER,
    heat_factor     DECIMAL(4,3),
    estimated_min   DECIMAL(10,2) NOT NULL,
    estimated_rec   DECIMAL(10,2) NOT NULL,
    estimated_max   DECIMAL(10,2) NOT NULL,
    detail_json     JSONB,
    source          SMALLINT    NOT NULL DEFAULT 1,
    created_at      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_estimate_user ON ai_estimate_log (user_id, created_at);
CREATE INDEX idx_estimate_product ON ai_estimate_log (product_id);

COMMENT ON TABLE  ai_estimate_log IS 'AI估价记录表';
COMMENT ON COLUMN ai_estimate_log.detail_json IS '系数明细(JSONB)';
COMMENT ON COLUMN ai_estimate_log.source IS '来源 1规则引擎 2大模型 3混合';

-- ------------------------------------------------------------
-- 14. AI 自动填表草稿表（一键发布链路）
-- ------------------------------------------------------------
CREATE TABLE ai_publish_draft (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL,
    draft_json  JSONB       NOT NULL,
    status      SMALLINT    NOT NULL DEFAULT 0,
    product_id  BIGINT,
    deleted     SMALLINT    NOT NULL DEFAULT 0,
    created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_draft_user ON ai_publish_draft (user_id, status, created_at);

COMMENT ON TABLE  ai_publish_draft IS 'AI自动填表草稿表';
COMMENT ON COLUMN ai_publish_draft.status IS '状态 0待确认 1已发布 2已过期 3已放弃';

-- ============================================================
-- updated_at 触发器（所有含 updated_at 的表）
-- ============================================================
CREATE TRIGGER trg_user_updated_at      BEFORE UPDATE ON "user"          FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_category_updated_at  BEFORE UPDATE ON category        FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_product_updated_at   BEFORE UPDATE ON product         FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_order_updated_at     BEFORE UPDATE ON trade_order     FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_credit_updated_at    BEFORE UPDATE ON carbon_credit   FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_draft_updated_at     BEFORE UPDATE ON ai_publish_draft FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ============================================================
-- 种子数据：分类（含 AI 估价参数）+ 测试用户
-- ============================================================
INSERT INTO category (id, parent_id, name, icon, base_price, depreciation_rate, heat_weight, sort_order) VALUES
(1, 0, '数码电子', NULL, 3000.00, 0.1500, 1.200, 1),
(2, 0, '图书教材', NULL, 60.00,  0.3000, 0.800, 2),
(3, 0, '生活用品', NULL, 150.00, 0.2000, 1.000, 3),
(4, 0, '运动户外', NULL, 400.00, 0.1800, 0.900, 4),
(5, 0, '服饰鞋包', NULL, 200.00, 0.2500, 1.000, 5),
(6, 0, '美妆个护', NULL, 180.00, 0.2800, 0.850, 6),
(7, 0, '乐器',     NULL, 1200.00, 0.1200, 0.750, 7),
(8, 0, '其他',     NULL, 100.00, 0.2000, 0.800, 8),
(11, 1, '手机',    NULL, 3000.00, 0.1800, 1.300, 11),
(12, 1, '笔记本电脑', NULL, 4500.00, 0.1400, 1.100, 12),
(13, 1, '平板',    NULL, 2500.00, 0.1600, 1.000, 13),
(14, 1, '耳机/音响', NULL, 500.00, 0.2000, 1.100, 14),
(21, 2, '专业课教材', NULL, 60.00, 0.3000, 0.900, 21),
(22, 2, '考研/考证', NULL, 80.00, 0.2500, 0.950, 22),
(31, 3, '宿舍小家电', NULL, 200.00, 0.2200, 1.000, 31),
(32, 3, '家具收纳', NULL, 120.00, 0.2500, 0.900, 32);

-- 修正序列（显式 id 插入后同步序列）
SELECT setval('category_id_seq', (SELECT MAX(id) FROM category));

INSERT INTO "user" (id, student_no, username, name, nickname, credit_score) VALUES
(1, '24320209', 'tianbo', '田博', '田博', 100),
(2, '24320201', 'chensihan', '陈思瀚', '陈思瀚', 100),
(3, '24320202', 'fanshengzhou', '范胜洲', '范胜洲', 100),
(4, '24320203', 'xujiakai', '徐家凯', '徐家凯', 100),
(5, '24320204', 'lintianchu', '林天楚', '林天楚', 100);

SELECT setval('"user_id_seq"', (SELECT MAX(id) FROM "user"));
